### ISSUE TITLE
"Cost of a 51 percent attack" is wildly wrong...

### ISSUE THREAD

**Issue by noamnelke** [snario/awesome-cryptoeconomics#4]
Other than the hashrate, nothing on that page is correct...

- Cheapest kWh rate - based on [Wikipedia](https://en.wikipedia.org/wiki/Electricity_pricing#Global_comparison) there are places with much cheaper electricity.
- Antminer S5+ - the [Antminer S9](https://shop.bitmain.com/specifications.htm?name=antminer_s9_asic_bitcoin_miner) costs half, has double the hashrate and uses a 1/3 of the electricity.

But more importantly:

- It's wrong to assume that an attacker would need to buy the equipment from scratch - a mining pool could be the attacker.
- The site completely ignores the **opportunity cost** of running the attack instead of mining.

And most importantly, I consider this site to have low quality because:

- No transparency - it doesn't say how it does the calculation.
- No sources cited - for the actual data used.
- Not open to corrections and feedback - there's no place to report errors to them.
[update: just found a contact email and sent them this, let's see how they respond]

I suggest either removing the reference, or leaving it for the entertainment value and adding a disclaimer with the issues listed above.

**Comment by cleanunicorn** [comment]
People ignore the fact that any blockchain node also validates the blocks, it doesn't just accept the longest chain.

In the case of having 51% of miners generating invalid blocks the rest of 49% of miners will just ignore the chain, thus a fork would be created: a valid chain and an invalid chain.

Running at home your own node will ignore the longest, incorrect, chain and will accept the blocks on the shorter, valid chain.

The attackers create blocks that will not be accepted by any node, thus creating a universe that only they live in, forking themselves out of valid existence.

**Comment by noamnelke** [comment]
update: I contacted the site and they fixed all of the above (other than the cost of a miner, which is currently wrong on the bitcoin wiki).

I've provided them with even more feedback and they seem receptive.

The page is much better now, so I'm closing this issue...

**Comment by noamnelke** [comment]
@cleanunicorn I think you're missing the purpose of a 51% attack... Attackers using it aren't supposed to steal bitcoin from random wallets, nor create bitcoin out of thin air. If they try - what you said would happen.

The danger of a 51% attack is the ability to double spend during the attack. If I command a majority of hashpower I can do this to you:

I sell you bitcoin for cash. Say you insist on 6 confirmations. I send you the bitcoin, we wait an hour and you get your 6 confirmations. You give me the cash. I leave.

While we were waiting, I secretly created another transaction sending the same bitcoin to myself (at another address), I didn't broadcast this transaction, but instead I started using my hashpower to mine an alternative chain with my transaction instead of yours. Since I have more hashpower than the honest miners, I'm going to have a longer valid chain (it won't have a double spend since it has my transaction and not yours, so all is fine).

After I've left with the money, the public chain has 6 blocks in it confirming the transfer to you, but my chain is slightly longer or statistically it will be very soon. Once that happens I publish my chain (I'm far from you by this point, with the cash). Everyone sees this chain is longer and accepts it, and discards the previous chain, and you lose your bitcoin (and cash).

For this to be economical the benefit I get from the attack (your cash) has to be greater than the cost of the attack (what the site calculates). If you'd trade millions/billions of $ with me, it may be worth it. The higher that number the more secure bitcoin is.
